#!/bin/sh

# script/bootstrap: bootstrap application for first usage

set -e

cd "$(dirname "$0")/.."

glide install --force --strip-vendor --skip-test

rm -rf ./vendor/k8s.io/{apiserver,apimachinery,client-go}

cp -r ./vendor/k8s.io/kubernetes/staging/src/k8s.io/{apiserver,apimachinery,client-go} ./vendor/k8s.io
